# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skill.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skill.proto',
  package='settingData',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0bskill.proto\x12\x0bsettingData\"4\n\x05Skill\x12\x0f\n\x07skillId\x18\x01 \x02(\x05\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x0c\n\x04\x64\x65sc\x18\x03 \x02(\t\"/\n\nSkillArray\x12!\n\x05skill\x18\x01 \x03(\x0b\x32\x12.settingData.Skill')
)




_SKILL = _descriptor.Descriptor(
  name='Skill',
  full_name='settingData.Skill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skillId', full_name='settingData.Skill.skillId', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='settingData.Skill.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='desc', full_name='settingData.Skill.desc', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=80,
)


_SKILLARRAY = _descriptor.Descriptor(
  name='SkillArray',
  full_name='settingData.SkillArray',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skill', full_name='settingData.SkillArray.skill', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=129,
)

_SKILLARRAY.fields_by_name['skill'].message_type = _SKILL
DESCRIPTOR.message_types_by_name['Skill'] = _SKILL
DESCRIPTOR.message_types_by_name['SkillArray'] = _SKILLARRAY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Skill = _reflection.GeneratedProtocolMessageType('Skill', (_message.Message,), dict(
  DESCRIPTOR = _SKILL,
  __module__ = 'skill_pb2'
  # @@protoc_insertion_point(class_scope:settingData.Skill)
  ))
_sym_db.RegisterMessage(Skill)

SkillArray = _reflection.GeneratedProtocolMessageType('SkillArray', (_message.Message,), dict(
  DESCRIPTOR = _SKILLARRAY,
  __module__ = 'skill_pb2'
  # @@protoc_insertion_point(class_scope:settingData.SkillArray)
  ))
_sym_db.RegisterMessage(SkillArray)


# @@protoc_insertion_point(module_scope)
